version: '3'

services:
  kakdela-nginx:
    build: build/nginx
    image: kakdela/nginx
    volumes:
     - "./volumes/nginx/log/:/var/log/nginx/"
     - "./build/nginx/kakdela.local.conf:/etc/nginx/conf.d/default.conf:ro"
     - "..:/kakdela:ro"
    ports:
     - "127.0.0.1:80:80"
    networks:
     - kakdela
  kakdela-node-client:
    build: build/node
    image: kakdela/node
    volumes:
      - "../frontend:/src"
    ports:
      - "127.0.0.1:3334:3333"
    networks:
      - kakdela
  kakdela-node-server:
    build: build/node
    image: kakdela/node
    volumes:
     - "../backend_old:/src"
    ports:
     - "127.0.0.1:3335:3333"
     - "9229:9229"
    networks:
     - kakdela
  kakdela-postgresql:
    build: build/postgresql
    image: kakdela/postgresql
    volumes:
     - "./volumes/pgdata:/var/lib/postgresql/data"
     - "./volumes/data:/opt/data"
    tmpfs:
     - /run
     - /tmp
    ports:
     - "127.0.0.1:5432:5432"
    networks:
     - kakdela
  kakdela-redis:
    image: redis:3.0
    ports:
     - "127.0.0.1:6379:6379"
    networks:
     - kakdela

networks:
  kakdela:
    external: true
