#!/usr/bin/env bash

. $(dirname $0)/script/functions.sh

if [[ $1 == "createuser" ]]; then
    pg -u postgres psql -h kakdela -U postgres -f /docker-entrypoint-initdb.d/create_db.sql
    exit 0
fi

if [[ -z "$@" ]]; then
    pg psql -h kakdela-postgresql -U kakdela -d kakdela
    exit 0
fi

pg psql "$@"
